/*
  Wearable FMV Platform Control
  Arduino control code for the Buck-Boost module and RemoteXY interface
*/

/*
  RemoteXY configuration
  The following configuration code is automatically generated by the 
  RemoteXY application according to the graphical user interface design.
*/

#define REMOTEXY_MODE__ESP32CORE_BLE
#include <BLEDevice.h> 
#define REMOTEXY_BLUETOOTH_NAME "REMOTEXY"
#include <RemoteXY.h>

// RemoteXY GUI configuration  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 131 bytes V19 
  { 255,4,0,0,0,124,0,19,0,0,0,0,31,1,106,200,1,1,5,0,
  1,22,42,62,21,1,2,31,77,111,100,101,32,49,58,32,60,56,48,32,
  72,122,0,1,22,82,62,22,1,190,31,77,111,100,101,32,50,58,32,49,
  48,48,32,72,122,0,1,22,123,62,22,1,246,31,77,111,100,101,32,51,
  58,32,49,50,48,32,72,122,0,129,8,17,93,9,192,8,70,114,101,113,
  117,101,110,99,121,32,99,111,110,116,114,111,108,32,70,77,86,0,1,38,
  159,28,17,1,1,31,83,84,79,80,0 };
  
/*
  This structure defines all the variables and events of the RemoteXY interface
  (Structure automatically generated by RemoteXY) 
 */
struct {

  // Input variables
  uint8_t button_01;  // =1 if button pressed, else =0
  uint8_t button_02;  // =1 if button pressed, else =0
  uint8_t button_03;  // =1 if button pressed, else =0
  uint8_t button_04;  // =1 if button pressed, else =0

  // Connection flag
  uint8_t connect_flag;  // =1 if connected, else =0

} RemoteXY;   
#pragma pack(pop)


// Pin definition

const int VS1_PIN = D6;      // Buck-Boost voltage selection pin VS1
const int VS2_PIN = D5;      // Buck-Boost voltage selection pin VS2
const int VS3_PIN = D4;      // Buck-Boost voltage selection pin VS3
const int RUN_PIN = D3;      // HIGH = Buck-Boost enabled; LOW = Buck-Boost disabled
const int PWM_PIN = D7;      // PWM control pin of the Buck-Boost module
const int MOSFET_PIN = D9;   // Motor ON/OFF control through the MOSFET

int currentMode = 0;         // Stores the currently selected operating mode


void setup() {

  RemoteXY_Init();

  pinMode(RUN_PIN, OUTPUT);
  pinMode(VS1_PIN, OUTPUT);
  pinMode(VS2_PIN, OUTPUT);
  pinMode(VS3_PIN, OUTPUT);
  pinMode(PWM_PIN, OUTPUT);
  pinMode(MOSFET_PIN, OUTPUT);

  digitalWrite(RUN_PIN, HIGH);      // Enable Buck-Boost module
  digitalWrite(PWM_PIN, HIGH);      // Keep Buck-Boost PWM control pin active
  digitalWrite(MOSFET_PIN, LOW);    // Motor off at startup
  
}

/*
  Function to select the Buck-Boost output voltage:
  The Buck-Boost module changes its output voltage depending on
  the HIGH/LOW levels applied to VS1, VS2 and VS3.
  Only the output voltages used in the final wearable FMV 
  platform are implemented.
*/

void setBoosterVoltage(int voltage) {

  // 3.3 V : VS3 = 0  VS2 = 0 VS1 = 1
  if (voltage == 33) {
    digitalWrite(VS3_PIN, LOW);
    digitalWrite(VS2_PIN, LOW);
    digitalWrite(VS1_PIN, HIGH);
  }

  // 5.0 V : VS3 = 0  VS2 = 1  VS1 = 1
  if (voltage == 5) {
    digitalWrite(VS3_PIN, LOW);
    digitalWrite(VS2_PIN, HIGH);
    digitalWrite(VS1_PIN, HIGH);
  }
  
  // 6.9 V : VS3 = 1  VS2 = 0  VS1 = 0
  if (voltage == 69) {
    digitalWrite(VS3_PIN, HIGH);
    digitalWrite(VS2_PIN, LOW);
    digitalWrite(VS1_PIN, LOW);
  }
}

// Function to apply the selected stimulation mode

void applyMode(int mode){

  currentMode = mode;

  // Mode 1: approximately 70 Hz
  if (mode == 1) {
    setBoosterVoltage(33);
    digitalWrite(PWM_PIN, HIGH);
    digitalWrite(MOSFET_PIN, HIGH);
  }

  // Mode 2: approximately 100 Hz
  if (mode == 2) {
    setBoosterVoltage(5);
    digitalWrite(PWM_PIN, HIGH);
    digitalWrite(MOSFET_PIN, HIGH);
  }

  // Mode 3: approximately 120 Hz
  if (mode == 3) {
    setBoosterVoltage(69);
    digitalWrite(PWM_PIN, HIGH);     
    digitalWrite(MOSFET_PIN, HIGH);
  }

  // Stop mode: motor off
  if (mode == 4) {
    digitalWrite(PWM_PIN, HIGH);     
    digitalWrite(MOSFET_PIN, LOW);
  }

}

  

void loop() {

  RemoteXYEngine.handler();

  if (RemoteXY.button_01) { //Mode 1 button 
    applyMode(1);
  }

  if (RemoteXY.button_02) { //Mode 2 button 
    applyMode(2);
  }

  if (RemoteXY.button_03) { //Mode 3 button 
    applyMode(3);
  }

  if (RemoteXY.button_04) { //Stop button 
    applyMode(4);
  }

  RemoteXYEngine.delay(50);

}
